apiVersion: v1
data:
  IBM_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  IBM_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-storage
  IBM_SUBSCRIPTION_CHANNEL: stable-v1
  IBM_SUBSCRIPTION_NAME: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_PACKAGE: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_STARTINGCSV: ibm-storage-odf-operator.v0.2.1
  OCS_CSV_NAME: ocs-operator.v4.9.0
  OCS_SUBSCRIPTION_PACKAGE: ocs-operator
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 4fd470de.openshift.io
kind: ConfigMap
metadata:
  name: odf-operator-manager-config
