apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- odf-operator.clusterserviceversion.yaml
patchesStrategicMerge:
- odf-operator.csv.icon.yaml
- odf-operator.csv.card-description.yaml
